services:
  flight_path:
    build:
      context: .. # this allows us to have access to the complete repository and not only the docker folder
      dockerfile: docker/Dockerfile
    working_dir: /code/FlightPath # Set the working dir to where the code lives
    tty: true # Enable interactive terminal (useful for shell access)
    # Only add folders and files we want to have access to inside the container
    volumes:
      - ../coverage:/coverage
      - ../data:/code/FlightPath/data
      - ../doxygen:/code/FlightPath/doxygen
      - ../include:/code/FlightPath/include
      - ../src:/code/FlightPath/src
      - ../tests:/code/FlightPath/tests
      - ../CMakeLists.txt:/code/FlightPath/CMakeLists.txt
      - ../CMakePresets.json:/code/FlightPath/CMakePresets.json
