name: Build and Test

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Configure (CI)
      run: cmake --preset ci

    - name: Build (CI)
      run: cmake --build --preset ci

    - name: Test
      run: cmake --build --preset ci --target test