name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Configure
        run: cmake --preset release-app

      - name: Build
        run: cmake --build --preset build-app --target FlightPath

