name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ develop ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install llvm
        run: sudo apt-get install llvm catch2

      - name: Configure
        run: cmake --preset tests-coverage

      - name: Build
        run: cmake --build --preset build-tests-coverage --target RunTests

      - name: Run Tests
        working-directory: build/tests-coverage/tests
        run: ctest
